### ISSUE TITLE
Arduino Lionardo error? (pn532)

### ISSUE THREAD

**Issue by datboi2008** [CrazyRedMachine/PN5180-cardio#10]
when compiling before the upload, it gives me this error.

In file included from C:\Users\Tarquin G\Documents\Arduino\libraries\Adafruit_TinyUSB_Arduino-master\src/tusb_option.h:190:0,
                 from C:\Users\Tarquin G\Documents\Arduino\libraries\Keyboard\src/common/tusb_common.h:70,
                 from C:\Users\Tarquin G\Documents\Arduino\libraries\Keyboard\src/HID.h:34,
                 from C:\Users\Tarquin G\Documents\Arduino\libraries\Keyboard\src/Keyboard.h:25,
                 from F:\PN5180-cardio-PN532\PN5180-cardio-PN532\PN532-cardio\PN532-cardio.ino:6:
C:\Users\Tarquin G\Documents\Arduino\libraries\Adafruit_TinyUSB_Arduino-master\src/tusb_config.h:46:4: error: #error TinyUSB Arduino Library does not support your core yet
   #error TinyUSB Arduino Library does not support your core yet
    ^~~~~

exit status 1

Compilation error: exit status 1

(NOTE: Im new to arduino and just bought the leonardo just for the purpose of a card reader.)

**Comment by CrazyRedMachine** [comment]
select arduino leonardo as your board type, this code is not for the TinyUSB stack but regular arduino PluggableUSB

**Comment by datboi2008** [comment]
after removing the tinyUSB, i just get this error

In file included from C:\Users\Tarquin G\Documents\Arduino\libraries\Keyboard\src/HID.h:34:0,
                 from C:\Users\Tarquin G\Documents\Arduino\libraries\Keyboard\src/Keyboard.h:25,
                 from F:\PN5180-cardio-PN532\PN5180-cardio-PN532\PN532-cardio\PN532-cardio.ino:6:
C:\Users\Tarquin G\Documents\Arduino\libraries\Keyboard\src/common/tusb_common.h:70:10: fatal error: tusb_option.h: No such file or directory
 #include "tusb_option.h"
          ^~~~~~~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: exit status 1

**Comment by datboi2008** [comment]
i went through many errors before of missing .h files and had to source them all and put them in different folders before

**Comment by datboi2008** [comment]
Nvm i reinstalled the keyboard library and it uploaded. time to test...

**Comment by datboi2008** [comment]
every time i plug it in, the log of spicetools says it detects cardio but it could not "open" the device. ive tried 2 different wirings, which wiring am i supposed to use

***EDIT: it seems to work, but it still says it cant open the device

**Comment by CrazyRedMachine** [comment]
this msg is probably refering to another interface of the device, if card scan works then i wouldn't bother about the error message
