### ISSUE TITLE
Cardio works with every game except DDR X2 (Pn532 specifically)

### ISSUE THREAD

**Issue by datboi2008** [CrazyRedMachine/PN5180-cardio#11]
The cardio reader I have setup is doing great and I have had no problems with it, but i have noticed that with one game, it won't work. In DDR X2, when in J.A.A (HD mode), the spicetools console says it read the card, while the game won't pick it up at all. in J.B.A (SD mode), it will read the card, but give me an error telling me to check the card. In both of these modes, binding a key to insert a card.txt file works without flaw. I was wondering if this issue has already been discovered and if there is a fix.

**Comment by CrazyRedMachine** [comment]
this appears to be a spicetools issue, not a cardio issue.
cardio is just a device whose role is to send an hid report with the nfc card id you just scanned. it has no awareness of any game you might be running
