### ISSUE TITLE
pn5180 mifare authentication key timeout

### ISSUE THREAD

**Issue by jhembed** [CrazyRedMachine/PN5180-cardio#5]
Hello, have you tested the identity authentication of ISO14443 agreement? When I tested, I found the authentication timeout and returned the time error code 2.

**Comment by CrazyRedMachine** [comment]
hi, thanks for bringing this issue to my attention :)

is it a problem you encounter with https://github.com/tueddy/PN5180-Library/tree/ISO14443 as well?

please try the example sketch there and see if you can read a mifare uuid in serial monitor.

**Comment by jhembed** [comment]
I've got the UID, and when I authenticate KEYA with UID, the return value is 2

![image](https://user-images.githubusercontent.com/30489909/102742762-af47c500-4390-11eb-9769-36876b12e8bf.png)

**Comment by CrazyRedMachine** [comment]
sounds like it is not a problem related to pn5180-cardio project then...

that being said, i can still have a quick look if you share the code in a gist or in another repository.

**Comment by jhembed** [comment]
Yes, there is no problem with the PN5180-Cardio project.

However, this project does not have the operation of the authentication KEY, so my own project is stuck here.

I have done STM32 transplantation according to the PN5180-Cardio project. After testing, I have achieved the reading and writing of ISO15693. Now what I need to solve is the identity authentication of ISO14443.


Here's my code: https://github.com/wowyyy/HAL_STM32_PN5180_SPI_DEMO

**Comment by CrazyRedMachine** [comment]
i've reopened the thread on your project instead and will resume conversation there. I'm closing this issue since it's not related to PN5180-cardio
