### ISSUE TITLE
Raspberry Pi Pico?

### ISSUE THREAD

**Issue by datboi2008** [CrazyRedMachine/PN5180-cardio#8]
Does this work on Pi Pico? ive been trying to get this to flash onto my pico forever but it keeps giving me errors about missing files and now its 
giving me this error

WARNING: library Keyboard claims to run on avr, samd, sam architecture(s) and may be incompatible with your current board which runs on mbed_rp2040 architecture(s).
F:\PN5180-cardio-PN532\PN5180-cardio-PN532\PN532-cardio\PN532-cardio.ino:12:1: error: 'Cardio_' does not name a type
 Cardio_ Cardio;
 ^~~~~~~
F:\PN5180-cardio-PN532\PN5180-cardio-PN532\PN532-cardio\PN532-cardio.ino: In function 'void setup()':
F:\PN5180-cardio-PN532\PN5180-cardio-PN532\PN532-cardio\PN532-cardio.ino:63:3: error: 'Cardio' was not declared in this scope
   Cardio.begin(false);
   ^~~~~~
F:\PN5180-cardio-PN532\PN5180-cardio-PN532\PN532-cardio\PN532-cardio.ino: In function 'void loop()':
F:\PN5180-cardio-PN532\PN5180-cardio-PN532\PN532-cardio\PN532-cardio.ino:100:7: error: 'Cardio' was not declared in this scope
       Cardio.setUID(2, idm);
       ^~~~~~
F:\PN5180-cardio-PN532\PN5180-cardio-PN532\PN532-cardio\PN532-cardio.ino:117:5: error: 'Cardio' was not declared in this scope
     Cardio.setUID(1, hid_data);
     ^~~~~~

exit status 1

Compilation error: 'Cardio_' does not name a type

**Comment by CrazyRedMachine** [comment]
pico is not supported, please check the readme there's a "supported device" list

**Comment by datboi2008** [comment]
So the Pico isn't even supported with the API version?

**Comment by CrazyRedMachine** [comment]
yea, pico is too different from arduino. there's a pico version of this project in the works but currently not my priority..
